USE [master]
GO

/****** Object:  Database [FitMeDB]    Script Date: 10/14/2022 2:29:09 PM ******/
CREATE DATABASE [FitMeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FitMeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\FitMeDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FitMeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\FitMeDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FitMeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FitMeDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FitMeDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FitMeDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FitMeDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FitMeDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [FitMeDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FitMeDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FitMeDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FitMeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FitMeDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FitMeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FitMeDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FitMeDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FitMeDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FitMeDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FitMeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FitMeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FitMeDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FitMeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FitMeDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FitMeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FitMeDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FitMeDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FitMeDB] SET  MULTI_USER 
GO

ALTER DATABASE [FitMeDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FitMeDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FitMeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FitMeDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FitMeDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FitMeDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FitMeDB] SET  READ_WRITE 
GO



Use FitMeDB
go
 

create table Gyms
(
Id int identity primary key not null,
Name nvarchar(128) not null,
Address nvarchar(max) not null,
Phone nvarchar(256) null
)
go


create table Trainers
(
Id int identity primary key not null,
FirstName nvarchar(128) not null,
LastName nvarchar(256) not null,
Gender nvarchar(50) not null,
Picture nvarchar(256) default 'DefaultPicture.jpg'
)
go

create table TrainerGym
(
Id int identity primary key not null,
TrainerId int not null,
GymId int not null,
foreign key (TrainerId) references Trainers(Id),
foreign key (GymId) references Gyms(Id)
)
go


create table GroupTrainings
(
Id int identity primary key not null,
Name nvarchar(256) not null,
Description nvarchar (max) null,
TrainerId int not null,
GymId int not null,
foreign key (GymId) references Gyms(Id),
foreign key (TrainerId) references Trainers(Id)
)
go

