//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitMeApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitMeApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wwwroot\\TextFiles\\ApproveApplicationMessage.txt.
        /// </summary>
        internal static string ApproveAppMessagePath {
            get {
                return ResourceManager.GetString("ApproveAppMessagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \wwwroot\ExcelFiles\Blanks\AttendanceChart.xlsx.
        /// </summary>
        internal static string AttendanceChartBlankPath {
            get {
                return ResourceManager.GetString("AttendanceChartBlankPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/images/defaultAvatar.jpg.
        /// </summary>
        internal static string DefaultAvatarPath {
            get {
                return ResourceManager.GetString("DefaultAvatarPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \wwwroot\Python\DietJournal.py.
        /// </summary>
        internal static string DietJournalPyPath {
            get {
                return ResourceManager.GetString("DietJournalPyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wwwroot\\Content\\images\\healthyFood2.jpg.
        /// </summary>
        internal static string DietReportImagePath {
            get {
                return ResourceManager.GetString("DietReportImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wwwroot\TextFiles\GroupClassesDescription.txt.
        /// </summary>
        internal static string GroupClassesDescriptionPath {
            get {
                return ResourceManager.GetString("GroupClassesDescriptionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Subscriptions/gym.jpg.
        /// </summary>
        internal static string GymAccess {
            get {
                return ResourceManager.GetString("GymAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Subscriptions/gymDietMonitoring.jpg.
        /// </summary>
        internal static string GymAccessDietMonitoring {
            get {
                return ResourceManager.GetString("GymAccessDietMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Subscriptions/gymGroupTraining.jpg.
        /// </summary>
        internal static string GymAccessGroupTraining {
            get {
                return ResourceManager.GetString("GymAccessGroupTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Subscriptions/gymGroupTrainingDietMonitoring.jpg.
        /// </summary>
        internal static string GymAccessGroupTrainingDietMonitoring {
            get {
                return ResourceManager.GetString("GymAccessGroupTrainingDietMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wwwroot\\ExcelFiles\\Diet\\NutrientsList.xlsx.
        /// </summary>
        internal static string NutrientsTablePath {
            get {
                return ResourceManager.GetString("NutrientsTablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wwwroot\\TextFiles\\RejectApplicationMessage.txt.
        /// </summary>
        internal static string RejectAppMessagePath {
            get {
                return ResourceManager.GetString("RejectAppMessagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \wwwroot\ExcelFiles\Users.xlsx.
        /// </summary>
        internal static string UsersFileDestinationPath {
            get {
                return ResourceManager.GetString("UsersFileDestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Subscriptions/WorkAsTrainer.jpg.
        /// </summary>
        internal static string WorkAsTrainer {
            get {
                return ResourceManager.GetString("WorkAsTrainer", resourceCulture);
            }
        }
    }
}
